/*
 * Generated by gdbus-codegen 2.33.12. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "dbus-consolekit-seat.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.ConsoleKit.Seat
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:ConsoleKitSeat
 * @title: ConsoleKitSeat
 * @short_description: Generated C code for the org.freedesktop.ConsoleKit.Seat D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.ConsoleKit.Seat ---- */

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_get_id_OUT_ARG_sid =
{
  {
    -1,
    (gchar *) "sid",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_get_id_OUT_ARG_pointers[] =
{
  &_console_kit_seat_method_info_get_id_OUT_ARG_sid,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_get_id =
{
  {
    -1,
    (gchar *) "GetId",
    NULL,
    (GDBusArgInfo **) &_console_kit_seat_method_info_get_id_OUT_ARG_pointers,
    NULL
  },
  "handle-get-id",
  FALSE
};

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_get_sessions_OUT_ARG_sessions =
{
  {
    -1,
    (gchar *) "sessions",
    (gchar *) "ao",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_get_sessions_OUT_ARG_pointers[] =
{
  &_console_kit_seat_method_info_get_sessions_OUT_ARG_sessions,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_get_sessions =
{
  {
    -1,
    (gchar *) "GetSessions",
    NULL,
    (GDBusArgInfo **) &_console_kit_seat_method_info_get_sessions_OUT_ARG_pointers,
    NULL
  },
  "handle-get-sessions",
  FALSE
};

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_get_devices_OUT_ARG_devices =
{
  {
    -1,
    (gchar *) "devices",
    (gchar *) "a(ss)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_get_devices_OUT_ARG_pointers[] =
{
  &_console_kit_seat_method_info_get_devices_OUT_ARG_devices,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_get_devices =
{
  {
    -1,
    (gchar *) "GetDevices",
    NULL,
    (GDBusArgInfo **) &_console_kit_seat_method_info_get_devices_OUT_ARG_pointers,
    NULL
  },
  "handle-get-devices",
  FALSE
};

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_get_active_session_OUT_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_get_active_session_OUT_ARG_pointers[] =
{
  &_console_kit_seat_method_info_get_active_session_OUT_ARG_ssid,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_get_active_session =
{
  {
    -1,
    (gchar *) "GetActiveSession",
    NULL,
    (GDBusArgInfo **) &_console_kit_seat_method_info_get_active_session_OUT_ARG_pointers,
    NULL
  },
  "handle-get-active-session",
  FALSE
};

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_can_activate_sessions_OUT_ARG_can_activate =
{
  {
    -1,
    (gchar *) "can_activate",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_can_activate_sessions_OUT_ARG_pointers[] =
{
  &_console_kit_seat_method_info_can_activate_sessions_OUT_ARG_can_activate,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_can_activate_sessions =
{
  {
    -1,
    (gchar *) "CanActivateSessions",
    NULL,
    (GDBusArgInfo **) &_console_kit_seat_method_info_can_activate_sessions_OUT_ARG_pointers,
    NULL
  },
  "handle-can-activate-sessions",
  FALSE
};

static const _ExtendedGDBusArgInfo _console_kit_seat_method_info_activate_session_IN_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_method_info_activate_session_IN_ARG_pointers[] =
{
  &_console_kit_seat_method_info_activate_session_IN_ARG_ssid,
  NULL
};

static const GDBusAnnotationInfo _console_kit_seat_method_activate_session_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.GLib.Async",
  (gchar *) "",
  NULL
};

static const GDBusAnnotationInfo * const _console_kit_seat_method_activate_session_annotation_info_pointers[] =
{
  &_console_kit_seat_method_activate_session_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _console_kit_seat_method_info_activate_session =
{
  {
    -1,
    (gchar *) "ActivateSession",
    (GDBusArgInfo **) &_console_kit_seat_method_info_activate_session_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_console_kit_seat_method_activate_session_annotation_info_pointers
  },
  "handle-activate-session",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _console_kit_seat_method_info_pointers[] =
{
  &_console_kit_seat_method_info_get_id,
  &_console_kit_seat_method_info_get_sessions,
  &_console_kit_seat_method_info_get_devices,
  &_console_kit_seat_method_info_get_active_session,
  &_console_kit_seat_method_info_can_activate_sessions,
  &_console_kit_seat_method_info_activate_session,
  NULL
};

static const _ExtendedGDBusArgInfo _console_kit_seat_signal_info_active_session_changed_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_signal_info_active_session_changed_ARG_pointers[] =
{
  &_console_kit_seat_signal_info_active_session_changed_ARG_ssid,
  NULL
};

static const _ExtendedGDBusSignalInfo _console_kit_seat_signal_info_active_session_changed =
{
  {
    -1,
    (gchar *) "ActiveSessionChanged",
    (GDBusArgInfo **) &_console_kit_seat_signal_info_active_session_changed_ARG_pointers,
    NULL
  },
  "active-session-changed"
};

static const _ExtendedGDBusArgInfo _console_kit_seat_signal_info_session_added_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_signal_info_session_added_ARG_pointers[] =
{
  &_console_kit_seat_signal_info_session_added_ARG_ssid,
  NULL
};

static const _ExtendedGDBusSignalInfo _console_kit_seat_signal_info_session_added =
{
  {
    -1,
    (gchar *) "SessionAdded",
    (GDBusArgInfo **) &_console_kit_seat_signal_info_session_added_ARG_pointers,
    NULL
  },
  "session-added"
};

static const _ExtendedGDBusArgInfo _console_kit_seat_signal_info_session_removed_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_signal_info_session_removed_ARG_pointers[] =
{
  &_console_kit_seat_signal_info_session_removed_ARG_ssid,
  NULL
};

static const _ExtendedGDBusSignalInfo _console_kit_seat_signal_info_session_removed =
{
  {
    -1,
    (gchar *) "SessionRemoved",
    (GDBusArgInfo **) &_console_kit_seat_signal_info_session_removed_ARG_pointers,
    NULL
  },
  "session-removed"
};

static const _ExtendedGDBusArgInfo _console_kit_seat_signal_info_device_added_ARG_device =
{
  {
    -1,
    (gchar *) "device",
    (gchar *) "(ss)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_signal_info_device_added_ARG_pointers[] =
{
  &_console_kit_seat_signal_info_device_added_ARG_device,
  NULL
};

static const _ExtendedGDBusSignalInfo _console_kit_seat_signal_info_device_added =
{
  {
    -1,
    (gchar *) "DeviceAdded",
    (GDBusArgInfo **) &_console_kit_seat_signal_info_device_added_ARG_pointers,
    NULL
  },
  "device-added"
};

static const _ExtendedGDBusArgInfo _console_kit_seat_signal_info_device_removed_ARG_device =
{
  {
    -1,
    (gchar *) "device",
    (gchar *) "(ss)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _console_kit_seat_signal_info_device_removed_ARG_pointers[] =
{
  &_console_kit_seat_signal_info_device_removed_ARG_device,
  NULL
};

static const _ExtendedGDBusSignalInfo _console_kit_seat_signal_info_device_removed =
{
  {
    -1,
    (gchar *) "DeviceRemoved",
    (GDBusArgInfo **) &_console_kit_seat_signal_info_device_removed_ARG_pointers,
    NULL
  },
  "device-removed"
};

static const _ExtendedGDBusSignalInfo * const _console_kit_seat_signal_info_pointers[] =
{
  &_console_kit_seat_signal_info_active_session_changed,
  &_console_kit_seat_signal_info_session_added,
  &_console_kit_seat_signal_info_session_removed,
  &_console_kit_seat_signal_info_device_added,
  &_console_kit_seat_signal_info_device_removed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _console_kit_seat_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.ConsoleKit.Seat",
    (GDBusMethodInfo **) &_console_kit_seat_method_info_pointers,
    (GDBusSignalInfo **) &_console_kit_seat_signal_info_pointers,
    NULL,
    NULL
  },
  "console-kit-seat",
};


/**
 * console_kit_seat_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
console_kit_seat_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct;
}

/**
 * console_kit_seat_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #ConsoleKitSeat interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
console_kit_seat_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * ConsoleKitSeat:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link>.
 */

/**
 * ConsoleKitSeatIface:
 * @parent_iface: The parent interface.
 * @handle_activate_session: Handler for the #ConsoleKitSeat::handle-activate-session signal.
 * @handle_can_activate_sessions: Handler for the #ConsoleKitSeat::handle-can-activate-sessions signal.
 * @handle_get_active_session: Handler for the #ConsoleKitSeat::handle-get-active-session signal.
 * @handle_get_devices: Handler for the #ConsoleKitSeat::handle-get-devices signal.
 * @handle_get_id: Handler for the #ConsoleKitSeat::handle-get-id signal.
 * @handle_get_sessions: Handler for the #ConsoleKitSeat::handle-get-sessions signal.
 * @active_session_changed: Handler for the #ConsoleKitSeat::active-session-changed signal.
 * @device_added: Handler for the #ConsoleKitSeat::device-added signal.
 * @device_removed: Handler for the #ConsoleKitSeat::device-removed signal.
 * @session_added: Handler for the #ConsoleKitSeat::session-added signal.
 * @session_removed: Handler for the #ConsoleKitSeat::session-removed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link>.
 */

static void
console_kit_seat_default_init (ConsoleKitSeatIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * ConsoleKitSeat::handle-get-id:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetId">GetId()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_get_id() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-id",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_get_id),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ConsoleKitSeat::handle-get-sessions:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetSessions">GetSessions()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_get_sessions() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-sessions",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_get_sessions),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ConsoleKitSeat::handle-get-devices:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetDevices">GetDevices()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_get_devices() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-devices",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_get_devices),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ConsoleKitSeat::handle-get-active-session:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetActiveSession">GetActiveSession()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_get_active_session() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-active-session",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_get_active_session),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ConsoleKitSeat::handle-can-activate-sessions:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.CanActivateSessions">CanActivateSessions()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_can_activate_sessions() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-can-activate-sessions",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_can_activate_sessions),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * ConsoleKitSeat::handle-activate-session:
   * @object: A #ConsoleKitSeat.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_ssid: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.ActivateSession">ActivateSession()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call console_kit_seat_complete_activate_session() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-activate-session",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, handle_activate_session),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * ConsoleKitSeat::active-session-changed:
   * @object: A #ConsoleKitSeat.
   * @arg_ssid: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.ActiveSessionChanged">"ActiveSessionChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("active-session-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, active_session_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * ConsoleKitSeat::session-added:
   * @object: A #ConsoleKitSeat.
   * @arg_ssid: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.SessionAdded">"SessionAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("session-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, session_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * ConsoleKitSeat::session-removed:
   * @object: A #ConsoleKitSeat.
   * @arg_ssid: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.SessionRemoved">"SessionRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("session-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, session_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * ConsoleKitSeat::device-added:
   * @object: A #ConsoleKitSeat.
   * @arg_device: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.DeviceAdded">"DeviceAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, device_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  /**
   * ConsoleKitSeat::device-removed:
   * @object: A #ConsoleKitSeat.
   * @arg_device: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.DeviceRemoved">"DeviceRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ConsoleKitSeatIface, device_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

}

typedef ConsoleKitSeatIface ConsoleKitSeatInterface;
G_DEFINE_INTERFACE (ConsoleKitSeat, console_kit_seat, G_TYPE_OBJECT);

/**
 * console_kit_seat_emit_active_session_changed:
 * @object: A #ConsoleKitSeat.
 * @arg_ssid: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.ActiveSessionChanged">"ActiveSessionChanged"</link> D-Bus signal.
 */
void
console_kit_seat_emit_active_session_changed (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  g_signal_emit_by_name (object, "active-session-changed", arg_ssid);
}

/**
 * console_kit_seat_emit_session_added:
 * @object: A #ConsoleKitSeat.
 * @arg_ssid: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.SessionAdded">"SessionAdded"</link> D-Bus signal.
 */
void
console_kit_seat_emit_session_added (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  g_signal_emit_by_name (object, "session-added", arg_ssid);
}

/**
 * console_kit_seat_emit_session_removed:
 * @object: A #ConsoleKitSeat.
 * @arg_ssid: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.SessionRemoved">"SessionRemoved"</link> D-Bus signal.
 */
void
console_kit_seat_emit_session_removed (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  g_signal_emit_by_name (object, "session-removed", arg_ssid);
}

/**
 * console_kit_seat_emit_device_added:
 * @object: A #ConsoleKitSeat.
 * @arg_device: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.DeviceAdded">"DeviceAdded"</link> D-Bus signal.
 */
void
console_kit_seat_emit_device_added (
    ConsoleKitSeat *object,
    GVariant *arg_device)
{
  g_signal_emit_by_name (object, "device-added", arg_device);
}

/**
 * console_kit_seat_emit_device_removed:
 * @object: A #ConsoleKitSeat.
 * @arg_device: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Seat.DeviceRemoved">"DeviceRemoved"</link> D-Bus signal.
 */
void
console_kit_seat_emit_device_removed (
    ConsoleKitSeat *object,
    GVariant *arg_device)
{
  g_signal_emit_by_name (object, "device-removed", arg_device);
}

/**
 * console_kit_seat_call_get_id:
 * @proxy: A #ConsoleKitSeatProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetId">GetId()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_get_id_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_get_id_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_get_id (
    ConsoleKitSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetId",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_get_id_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_sid: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_get_id().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_get_id().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_id_finish (
    ConsoleKitSeat *proxy,
    gchar **out_sid,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_sid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_id_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_sid: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetId">GetId()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_get_id() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_id_sync (
    ConsoleKitSeat *proxy,
    gchar **out_sid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetId",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_sid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_sessions:
 * @proxy: A #ConsoleKitSeatProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetSessions">GetSessions()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_get_sessions_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_get_sessions_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_get_sessions (
    ConsoleKitSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetSessions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_get_sessions_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_sessions: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_get_sessions().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_get_sessions().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_sessions_finish (
    ConsoleKitSeat *proxy,
    gchar ***out_sessions,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_sessions);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_sessions_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_sessions: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetSessions">GetSessions()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_get_sessions() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_sessions_sync (
    ConsoleKitSeat *proxy,
    gchar ***out_sessions,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetSessions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_sessions);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_devices:
 * @proxy: A #ConsoleKitSeatProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetDevices">GetDevices()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_get_devices_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_get_devices_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_get_devices (
    ConsoleKitSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetDevices",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_get_devices_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_devices: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_get_devices().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_get_devices().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_devices_finish (
    ConsoleKitSeat *proxy,
    GVariant **out_devices,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(ss))",
                 out_devices);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_devices_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_devices: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetDevices">GetDevices()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_get_devices() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_devices_sync (
    ConsoleKitSeat *proxy,
    GVariant **out_devices,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetDevices",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(ss))",
                 out_devices);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_active_session:
 * @proxy: A #ConsoleKitSeatProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetActiveSession">GetActiveSession()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_get_active_session_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_get_active_session_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_get_active_session (
    ConsoleKitSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetActiveSession",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_get_active_session_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_ssid: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_get_active_session().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_get_active_session().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_active_session_finish (
    ConsoleKitSeat *proxy,
    gchar **out_ssid,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_ssid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_get_active_session_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_ssid: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetActiveSession">GetActiveSession()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_get_active_session() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_get_active_session_sync (
    ConsoleKitSeat *proxy,
    gchar **out_ssid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetActiveSession",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_ssid);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_can_activate_sessions:
 * @proxy: A #ConsoleKitSeatProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.CanActivateSessions">CanActivateSessions()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_can_activate_sessions_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_can_activate_sessions_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_can_activate_sessions (
    ConsoleKitSeat *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CanActivateSessions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_can_activate_sessions_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_can_activate: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_can_activate_sessions().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_can_activate_sessions().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_can_activate_sessions_finish (
    ConsoleKitSeat *proxy,
    gboolean *out_can_activate,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_can_activate);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_can_activate_sessions_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @out_can_activate: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.CanActivateSessions">CanActivateSessions()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_can_activate_sessions() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_can_activate_sessions_sync (
    ConsoleKitSeat *proxy,
    gboolean *out_can_activate,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CanActivateSessions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_can_activate);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_activate_session:
 * @proxy: A #ConsoleKitSeatProxy.
 * @arg_ssid: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.ActivateSession">ActivateSession()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_call_activate_session_finish() to get the result of the operation.
 *
 * See console_kit_seat_call_activate_session_sync() for the synchronous, blocking version of this method.
 */
void
console_kit_seat_call_activate_session (
    ConsoleKitSeat *proxy,
    const gchar *arg_ssid,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ActivateSession",
    g_variant_new ("(o)",
                   arg_ssid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * console_kit_seat_call_activate_session_finish:
 * @proxy: A #ConsoleKitSeatProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_call_activate_session().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with console_kit_seat_call_activate_session().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_activate_session_finish (
    ConsoleKitSeat *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_call_activate_session_sync:
 * @proxy: A #ConsoleKitSeatProxy.
 * @arg_ssid: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.ActivateSession">ActivateSession()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_call_activate_session() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
console_kit_seat_call_activate_session_sync (
    ConsoleKitSeat *proxy,
    const gchar *arg_ssid,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ActivateSession",
    g_variant_new ("(o)",
                   arg_ssid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * console_kit_seat_complete_get_id:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @sid: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetId">GetId()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_get_id (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation,
    const gchar *sid)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   sid));
}

/**
 * console_kit_seat_complete_get_sessions:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @sessions: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetSessions">GetSessions()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_get_sessions (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *sessions)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^ao)",
                   sessions));
}

/**
 * console_kit_seat_complete_get_devices:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @devices: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetDevices">GetDevices()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_get_devices (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation,
    GVariant *devices)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(ss))",
                   devices));
}

/**
 * console_kit_seat_complete_get_active_session:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @ssid: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.GetActiveSession">GetActiveSession()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_get_active_session (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation,
    const gchar *ssid)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   ssid));
}

/**
 * console_kit_seat_complete_can_activate_sessions:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @can_activate: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.CanActivateSessions">CanActivateSessions()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_can_activate_sessions (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation,
    gboolean can_activate)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   can_activate));
}

/**
 * console_kit_seat_complete_activate_session:
 * @object: A #ConsoleKitSeat.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Seat.ActivateSession">ActivateSession()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
console_kit_seat_complete_activate_session (
    ConsoleKitSeat *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * ConsoleKitSeatProxy:
 *
 * The #ConsoleKitSeatProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ConsoleKitSeatProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ConsoleKitSeatProxy.
 */

struct _ConsoleKitSeatProxyPrivate
{
  GData *qdata;
};

static void console_kit_seat_proxy_iface_init (ConsoleKitSeatIface *iface);

G_DEFINE_TYPE_WITH_CODE (ConsoleKitSeatProxy, console_kit_seat_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_CONSOLE_KIT_SEAT, console_kit_seat_proxy_iface_init));

static void
console_kit_seat_proxy_finalize (GObject *object)
{
  ConsoleKitSeatProxy *proxy = CONSOLE_KIT_SEAT_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (console_kit_seat_proxy_parent_class)->finalize (object);
}

static void
console_kit_seat_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
console_kit_seat_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
console_kit_seat_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_CONSOLE_KIT_SEAT);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_CONSOLE_KIT_SEAT);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
console_kit_seat_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  ConsoleKitSeatProxy *proxy = CONSOLE_KIT_SEAT_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
console_kit_seat_proxy_init (ConsoleKitSeatProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_CONSOLE_KIT_SEAT_PROXY, ConsoleKitSeatProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), console_kit_seat_interface_info ());
}

static void
console_kit_seat_proxy_class_init (ConsoleKitSeatProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (ConsoleKitSeatProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = console_kit_seat_proxy_finalize;
  gobject_class->get_property = console_kit_seat_proxy_get_property;
  gobject_class->set_property = console_kit_seat_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = console_kit_seat_proxy_g_signal;
  proxy_class->g_properties_changed = console_kit_seat_proxy_g_properties_changed;

}

static void
console_kit_seat_proxy_iface_init (ConsoleKitSeatIface *iface)
{
}

/**
 * console_kit_seat_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_proxy_new_finish() to get the result of the operation.
 *
 * See console_kit_seat_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
console_kit_seat_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_CONSOLE_KIT_SEAT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Seat", NULL);
}

/**
 * console_kit_seat_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with console_kit_seat_proxy_new().
 *
 * Returns: (transfer full) (type ConsoleKitSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
ConsoleKitSeat *
console_kit_seat_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return CONSOLE_KIT_SEAT (ret);
  else
    return NULL;
}

/**
 * console_kit_seat_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ConsoleKitSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
ConsoleKitSeat *
console_kit_seat_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_CONSOLE_KIT_SEAT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Seat", NULL);
  if (ret != NULL)
    return CONSOLE_KIT_SEAT (ret);
  else
    return NULL;
}


/**
 * console_kit_seat_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like console_kit_seat_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call console_kit_seat_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See console_kit_seat_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
console_kit_seat_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_CONSOLE_KIT_SEAT_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Seat", NULL);
}

/**
 * console_kit_seat_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to console_kit_seat_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with console_kit_seat_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type ConsoleKitSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
ConsoleKitSeat *
console_kit_seat_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return CONSOLE_KIT_SEAT (ret);
  else
    return NULL;
}

/**
 * console_kit_seat_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like console_kit_seat_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See console_kit_seat_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ConsoleKitSeatProxy): The constructed proxy object or %NULL if @error is set.
 */
ConsoleKitSeat *
console_kit_seat_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_CONSOLE_KIT_SEAT_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Seat", NULL);
  if (ret != NULL)
    return CONSOLE_KIT_SEAT (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * ConsoleKitSeatSkeleton:
 *
 * The #ConsoleKitSeatSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ConsoleKitSeatSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ConsoleKitSeatSkeleton.
 */

struct _ConsoleKitSeatSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_console_kit_seat_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_CONSOLE_KIT_SEAT);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_CONSOLE_KIT_SEAT);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_console_kit_seat_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_console_kit_seat_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_console_kit_seat_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _console_kit_seat_skeleton_vtable =
{
  _console_kit_seat_skeleton_handle_method_call,
  _console_kit_seat_skeleton_handle_get_property,
  _console_kit_seat_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
console_kit_seat_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return console_kit_seat_interface_info ();
}

static GDBusInterfaceVTable *
console_kit_seat_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_console_kit_seat_skeleton_vtable;
}

static GVariant *
console_kit_seat_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_console_kit_seat_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _console_kit_seat_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _console_kit_seat_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _console_kit_seat_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
console_kit_seat_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_console_kit_seat_on_signal_active_session_changed (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_ssid));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", "ActiveSessionChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_console_kit_seat_on_signal_session_added (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_ssid));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", "SessionAdded",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_console_kit_seat_on_signal_session_removed (
    ConsoleKitSeat *object,
    const gchar *arg_ssid)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_ssid));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", "SessionRemoved",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_console_kit_seat_on_signal_device_added (
    ConsoleKitSeat *object,
    GVariant *arg_device)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(@(ss))",
                   arg_device));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", "DeviceAdded",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_console_kit_seat_on_signal_device_removed (
    ConsoleKitSeat *object,
    GVariant *arg_device)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(@(ss))",
                   arg_device));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Seat", "DeviceRemoved",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void console_kit_seat_skeleton_iface_init (ConsoleKitSeatIface *iface);
G_DEFINE_TYPE_WITH_CODE (ConsoleKitSeatSkeleton, console_kit_seat_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_CONSOLE_KIT_SEAT, console_kit_seat_skeleton_iface_init));

static void
console_kit_seat_skeleton_finalize (GObject *object)
{
  ConsoleKitSeatSkeleton *skeleton = CONSOLE_KIT_SEAT_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (console_kit_seat_skeleton_parent_class)->finalize (object);
}

static void
console_kit_seat_skeleton_init (ConsoleKitSeatSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_CONSOLE_KIT_SEAT_SKELETON, ConsoleKitSeatSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
console_kit_seat_skeleton_class_init (ConsoleKitSeatSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (ConsoleKitSeatSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = console_kit_seat_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = console_kit_seat_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = console_kit_seat_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = console_kit_seat_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = console_kit_seat_skeleton_dbus_interface_get_vtable;
}

static void
console_kit_seat_skeleton_iface_init (ConsoleKitSeatIface *iface)
{
  iface->active_session_changed = _console_kit_seat_on_signal_active_session_changed;
  iface->session_added = _console_kit_seat_on_signal_session_added;
  iface->session_removed = _console_kit_seat_on_signal_session_removed;
  iface->device_added = _console_kit_seat_on_signal_device_added;
  iface->device_removed = _console_kit_seat_on_signal_device_removed;
}

/**
 * console_kit_seat_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Seat.top_of_page">org.freedesktop.ConsoleKit.Seat</link>.
 *
 * Returns: (transfer full) (type ConsoleKitSeatSkeleton): The skeleton object.
 */
ConsoleKitSeat *
console_kit_seat_skeleton_new (void)
{
  return CONSOLE_KIT_SEAT (g_object_new (TYPE_CONSOLE_KIT_SEAT_SKELETON, NULL));
}

